Repository spryker/rabbit-mq, pull requests merged in 2018-10, with the labels that each got.

#18 CC-116 Optimizing DataImporter speed
  src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
  src/Spryker/Client/RabbitMq/Model/Helper/QueueEstablishmentHelper.php
  src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php
  src/Spryker/Client/RabbitMq/RabbitMqConfig.php
  src/Spryker/Client/RabbitMq/RabbitMqFactory.php
  src/Spryker/Shared/RabbitMq/Transfer/rabbitmq.transfer.xml
Labels: request for review

#20 If a second connection object was destroyed this will create an error.
  src/Spryker/Client/RabbitMq/Model/Connection/Connection.php
Labels: bug, ready-for-release

#21 Feature/cc 116/master optimizing data importer speed
  src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
  src/Spryker/Client/RabbitMq/Model/Helper/QueueEstablishmentHelper.php
  src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php
  src/Spryker/Client/RabbitMq/RabbitMqConfig.php
  src/Spryker/Client/RabbitMq/RabbitMqFactory.php
  src/Spryker/Shared/RabbitMq/Transfer/rabbitmq.transfer.xml
Labels: improvement, ready-for-release
