Repository spryker/rabbit-mq, pull requests merged in 2019-02, with the labels that each got.

#25 TE-28: Fixed return types in Queue
  composer.json
  src/Spryker/Client/RabbitMq/Model/RabbitMqAdapter.php
Labels: bug, ready-for-release

#24 Extend Publisher and Consumer with application headers
  composer.json
  src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
  src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php
  src/Spryker/Shared/RabbitMq/Transfer/rabbitmq.transfer.xml
Labels: improvement, ready-for-release

#28 Updated composer.json.
  .travis.yml
  ci/travis.php.ini
  composer.json
  dependency.json
Labels: merge-only, request-AA-review

#29 Updated composer.json.
  composer.json
Labels: merge-only
